#!/usr/bin/env bash

if [ `whomai` != "root" ]; then
    echo "This script must be run as root (or via sudo)."
    exit 1
fi

hook=`pwd`/post-receive

cd ~git/

mkdir mini-meta-admin.git
cd mini-meta-admin.git

git --bare init
cp $hook hooks/

chown -R git:git .